### ISSUE TITLE
Mac / Linux installs

### ISSUE THREAD

**Issue by wayneashleyberry** [yostudios/Spritemapper#11]
plausible?

**Comment by lericson** [comment]
What does this even mean?

**Comment by jbergstroem** [comment]
wayneashleyberry: What isn't working for you right now? Most linux distros (and OS X since 10.3 something) already ship setuptools, which basically only is the only requirement. Download and unpack the tarball and run `python setup.py install` with proper sudo rights and you're done.

**Comment by wayneashleyberry** [comment]
haha, sorry guys...  misread the docs.

i just saw the link to the download page which only had windows installers.

noob :(
