### ISSUE TITLE
Optimize your CSS

### ISSUE THREAD

**Issue by jwerre** [yostudios/Spritemapper#14]
I haven't tried it yet but I was looking at your CSS on your homepage and you could optimize it a bit. Instead of declaring the background image multiple times just do it once in the "letter" class like so:

```
.letter {
  background: url(../img/awesome-font.png);
}
.letter.a {
  width: 22px; height: 17px;
  background-position: -x -y;
}
.letter.b {
   width: 15px; height: 17px;
   background-position: -x -y;
}
.letter.c {
   width: 16px; height: 17px;
   background-position: -x -y;
}
```

Great tool by the way!

**Comment by jnordberg** [comment]
I'ts very hard to do this without special syntax, and we want do avoid this. Closing for now
